class_names = ['Affenpinscher',
 'Afghan Hound',
 'Airedale Terrier',
 'Basenji',
 'Basset Hound',
 'Beagle',
 'Bedlington Terrier',
 'Bernese Mountain Dog',
 'Black and Tan Coonhound',
 'Bloodhound',
 'Border Collie',
 'Borzoi',
 'Bouvier des Flandres',
 'Boxer',
 'Bullmastiff',
 'Chihuahua',
 'Cocker Spaniel',
 'Dobermann',
 'Entlebucher Mountain Dog',
 'German Shepherd',
 'Golden Retriever',
 'Great Dane',
 'Ibizan Hound',
 'Irish Terrier',
 'Irish Water Spaniel',
 'Keeshond',
 'Labrador Retriever',
 'Lakeland Terrier',
 'Maltese',
 'Miniature Pinscher',
 'Miniature Schnauzer',
 'Otterhound',
 'Papillon',
 'Pekingese',
 'Pomeranian',
 'Pug',
 'Redbone Coonhound',
 'Rottweiler',
 'Saint Bernard',
 'Samoyed',
 'Schipperke',
 'Shetland Sheepdog',
 'Shih Tzu',
 'Siberian Husky',
 'Tibetan Mastiff',
 'Toy Fox Terrier',
 'Vizsla',
 'Weimaraner',
 'West Highland White Terrier',
 'Yorkshire Terrier']