features_softSet = {'Affenpinscher': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Afghan Hound': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Airedale Terrier': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Basenji': {'Sensitive': 0,
  'Introvert': 1,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 0},
 'Basset Hound': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 0},
 'Beagle': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Bedlington Terrier': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Bernese Mountain Dog': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Black and Tan Coonhound': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Bloodhound': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 0},
 'Border Collie': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Borzoi': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 0},
 'Bouvier des Flandres': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Boxer': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Bullmastiff': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 0,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 1,
  'Sport freak': 0,
  'Playfull': 1},
 'Chihuahua': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Cocker Spaniel': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Dobermann': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Entlebucher Mountain Dog': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'German Shepherd': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Golden Retriever': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Great Dane': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 0,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Ibizan Hound': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Irish Terrier': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Irish Water Spaniel': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Keeshond': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Labrador Retriever': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Lakeland Terrier': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Maltese': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Miniature Pinscher': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 0,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Miniature Schnauzer': {'Sensitive': 1,
  'Introvert': 1,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Otterhound': {'Sensitive': 0,
  'Introvert': 1,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Papillon': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Pekingese': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 0},
 'Pomeranian': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 0},
 'Pug': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 0,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 1,
  'Sport freak': 0,
  'Playfull': 1},
 'Redbone Coonhound': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Rottweiler': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Saint Bernard': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Samoyed': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 0,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Schipperke': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Shetland Sheepdog': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Shih Tzu': {'Sensitive': 0,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 0,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Siberian Husky': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 0,
  'Intelligent': 0,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 1,
  'Playfull': 1},
 'Tibetan Mastiff': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 0,
  'Sport freak': 0,
  'Playfull': 1},
 'Toy Fox Terrier': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Vizsla': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 1,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Weimaraner': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 0,
  'Curious': 1,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'West Highland White Terrier': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 1,
  'Friendly': 1,
  'Extravert': 0,
  'Quick learner': 1,
  'Intelligent': 1,
  'Communicative': 1,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1},
 'Yorkshire Terrier': {'Sensitive': 1,
  'Introvert': 0,
  'Family-oriented': 1,
  'Protective': 0,
  'Friendly': 0,
  'Extravert': 0,
  'Quick learner': 0,
  'Intelligent': 0,
  'Communicative': 0,
  'Curious': 0,
  'Energetic': 1,
  'Emotional': 1,
  'Sport freak': 1,
  'Playfull': 1}}